---
title: "KM"
output: html_document
date: '2022-12-31'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading libraries.
```{r}
library(tidyverse)
library(scales)
library(lubridate)
library(ggthemes)
library(janitor)
library(survival)
#install.packages("survminer")
library(survminer)
library(readxl)
```

Importing and cleaning data.
```{r}
winter_locs <- read_excel("/Users/jeffgrayum/Documents/BobwhiteData/BobwhiteData 2/All_Winter_Locs_Oct_2021_Traps.xlsx") %>%
  clean_names() %>%
  mutate(date = as_date(date))

winter_locs %>%
  view()

winter_locs %>%
  str()

#Adding binary status column ("A" = 1, and "D" = 0).
winter_locs$status_binary <- winter_locs$status

winter_locs$status_binary <- ifelse(winter_locs$status_binary == "A", 1, 0)

#Adding date column in numeric format
winter_locs$date <- lubridate::ymd(winter_locs$date)
winter_locs$date_numeric <- as.numeric(winter_locs$date - as.Date("2021-11-23"))

winter_locs %>%
  view()

```

First attempt at KM
```{r}
surv_object <- Surv(winter_locs$date_numeric, winter_locs$status_binary)
km_fit <- survfit(surv_object ~ 1)
ggsurvplot(km_fit, data = winter_locs)
```


